exports.schema = {
  // bill_feed: {},
  // bill_timeline: {},
  // bill_tracker_timeline: {},
  // bill_types: {},
  // bills: {},
  // bodies: {},
  // committees: {},
  // mime_types: {},
  // organizations: {},
  // parties: {},
  // people: {},
  // posts: {},
  // progress_status: {},
  // project_bills: {},
  // projects: {},
  // roll_calls: {},
  // senate: {},
  // session_bills: {},
  // sessions: {},
  sponsor_types: {},
  states: {},
  tracker_steps: {}
};
